version: '2'
services:
  broker:
    image: apache/kafka:latest
    hostname: broker
    container_name: broker
    ports:
      - '9092:9092'
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT_HOST://broker:9092,PLAINTEXT://broker:19092'
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@broker:29093'
      KAFKA_LISTENERS: 'CONTROLLER://:29093,PLAINTEXT_HOST://:9092,PLAINTEXT://:19092'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      CLUSTER_ID: '4L6g3nShT-eMCtK--X86sw'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
    ports:
      - '9200:9200'
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    mem_limit: 1 GB
  topics:
    image: apache/kafka:latest
    hostname: topics
    container_name: topics
    command: > 
      bash -c "
      /opt/kafka/bin/kafka-topics.sh --create --topic docstojson --bootstrap-server broker:9092
      "
    depends_on:
      - broker
      - elasticsearch
  kafka-conusumer:
    image: apache/kafka:latest
    command: /opt/kafka/bin/kafka-console-consumer.sh --bootstrap-server broker:9092 --topic docstojson
    depends_on:
      topics:
        condition: service_completed_successfully
  spark:
    build: ./spark
    hostname: spark
    container_name: spark
    environment:
      - OPENAI_API_KEY= ${API_KEY}  
    volumes:
      - ./spark/code/:/opt/tap-docs/
    command: > 
      /opt/spark/bin/spark-submit --conf spark.driver.extraJavaOptions="-Divy.cache.dir=/tmp -Divy.home=/tmp" --packages org.apache.spark:spark-sql-kafka-0-10_2.12:3.5.1,org.elasticsearch:elasticsearch-spark-30_2.12:8.13.4  /opt/tap-docs/docs_examinator.py
    depends_on:
      topics:
        condition: service_completed_successfully
  mastodon:
    build: ./python
    hostname: mastodon
    container_name: mastodon
    environment: 
      - outputdir=/mastodon-out
      - PYTHON_APP=mastodon.py
    volumes:
      - mastodon-out:/mastodon-out
      - ./files/:/usr/src/app/files
      - ./python/bin/:/usr/src/app/bin
    depends_on:
      topics:
        condition: service_completed_successfully
  fluentd:
    build: ./fluentd
    hostname: fluentd
    container_name: fluentd
    command: "-c /fluentd/etc/mastodon.conf"
    volumes:
      - ./fluentd/conf:/fluentd/etc
      - mastodon-out:/mastodon-out
    depends_on:
      topics:
        condition: service_completed_successfully
  kibana:
    hostname: kibana
    image: docker.elastic.co/kibana/kibana:8.13.4
    ports:
      - 5601:5601
    volumes:
      - ./kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
    depends_on:
        topics:
          condition: service_completed_successfully
volumes:
  mastodon-out: