FROM apache/spark:3.4.2

USER 0
RUN pip install numpy
RUN pip install openai
RUN pip install aiohttp
#RUN pip install spacy langdetect
#RUN python -m spacy download en_core_web_sm
#RUN python -m spacy download it_core_news_sm

USER spark